//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Enrolment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Enrolment()
        {
            this.Payments = new HashSet<Payment>();
            this.InstrumentHires = new HashSet<InstrumentHire>();
        }
    
        public int EnrolmentID { get; set; }
        public System.DateTime Date { get; set; }
        public int StudentID { get; set; }
        public int LessonBatchID { get; set; }
    
        public virtual Student Student { get; set; }
        public virtual Lessonbatch Lessonbatch { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payment> Payments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InstrumentHire> InstrumentHires { get; set; }
    }
}
