//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMMS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Ensemble
    {
        [Required]
        public int EnsembleID { get; set; }

        [Display(Name = "Student")]
        public int StudentID { get; set; }

        [Display(Name = "Ensemble Group")]
        public int EnsembleGroupID { get; set; }
    
        public virtual Student Student { get; set; }

        public virtual EnsembleGroup EnsembleGroup { get; set; }
    }
}
