//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeeStructire
    {
        public int FeeID { get; set; }
        public decimal StudentFee { get; set; }
        public decimal OpenFee { get; set; }
        public decimal HireFee { get; set; }
        public int InstrumentID { get; set; }
    
        public virtual Instrument Instrument { get; set; }
    }
}
