//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMMS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class InstrumentCondition
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InstrumentCondition()
        {
            this.InstrumentAsserts = new HashSet<InstrumentAssert>();
        }

        [Required]
        public int InstrumentConditionID { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Please provide a condition.")]
        [Display(Name = "Condition")]
        public string condition { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InstrumentAssert> InstrumentAsserts { get; set; }
    }
}
