//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMMS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class InstrumentAssert
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InstrumentAssert()
        {
            this.InstrumentHires = new HashSet<InstrumentHire>();
        }

        [Required]
        public int InstrumentAssertID { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Please provide an instrument.")]
        [Display(Name = "Instrument")]
        public int InstrumentID { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Please provide a condition.")]
        [Display(Name = "Condition")]
        public int InstrumentConditionID { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Please provide a code.")]
        [Display(Name = "Instrument Code")]
        public string InstrumentCode { get; set; }
    
        public virtual Instrument Instrument { get; set; }

        public virtual InstrumentCondition InstrumentCondition { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InstrumentHire> InstrumentHires { get; set; }
    }
}
