//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InstrumentHire
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InstrumentHire()
        {
            this.InstumentServices = new HashSet<InstumentService>();
        }
    
        public int InstrumentHireId { get; set; }
        public string Description { get; set; }
        public int InstrumentAssertID { get; set; }
        public int EnrolmentID { get; set; }
    
        public virtual Enrolment Enrolment { get; set; }
        public virtual InstrumentAssert InstrumentAssert { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InstumentService> InstumentServices { get; set; }
    }
}
