//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InstumentLevel
    {
        public int InstrumentID { get; set; }

        public int CourseLevelID { get; set; }

        public int UserID { get; set; }

        public int InstumentLevelID { get; set; }
    
        public virtual CourseLevel CourseLevel { get; set; }

        public virtual Instrument Instrument { get; set; }

        public virtual User User { get; set; }
    }
}
