//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InstumentService
    {
        public int InstumentServiceID { get; set; }
        public string Problem { get; set; }
        public System.DateTime Date { get; set; }
        public string Comments { get; set; }
        public int InstrumentHireId { get; set; }
        public int TechnicianID { get; set; }
    
        public virtual InstrumentHire InstrumentHire { get; set; }
        public virtual Technician Technician { get; set; }
    }
}
