//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lesson
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Lesson()
        {
            this.Lessonbatches = new HashSet<Lessonbatch>();
        }
    
        public int LessonID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int CourseLevelID { get; set; }
        public Nullable<int> InstrumentID { get; set; }
        public int LessonTypeID { get; set; }
    
        public virtual CourseLevel CourseLevel { get; set; }
        public virtual Instrument Instrument { get; set; }
        public virtual LessonType LessonType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lessonbatch> Lessonbatches { get; set; }
    }
}
