//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMMS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Music
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Music()
        {
            this.MusicSheets = new HashSet<MusicSheet>();
        }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Please provide music.")]
        [Display(Name = "Music")]
        public int MusicID { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Please provide a name.")]
        [Display(Name = "Name")]
        public string Name { get; set; }

        public string Description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MusicSheet> MusicSheets { get; set; }
    }
}
