//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PayList
    {
        public int PayListID { get; set; }
        public Nullable<decimal> Deduction { get; set; }
        public decimal NetPay { get; set; }
        public System.DateTime PaymentDate { get; set; }
        public int PayrollID { get; set; }
    
        public virtual Payroll Payroll { get; set; }
    }
}
