//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMMS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Payroll
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Payroll()
        {
            this.PayLists = new HashSet<PayList>();
        }
    
        public int PayrollID { get; set; }

        [Display(Name = "Pay Date")]
        public System.DateTime PayDate { get; set; }

        [Display(Name = "Gross Pay")]
        public decimal GrossPay { get; set; }

        [Display(Name = "User")]
        public int UserID { get; set; }

        [Display(Name = "Payment Status")]
        public int PaymentStatus { get; set; }

        [Display(Name = "Preparation Date")]
        public Nullable<System.DateTime> PreparationDate { get; set; }
    
        public virtual User User { get; set; }
        public virtual PaymentStatu PaymentStatu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PayList> PayLists { get; set; }
    }
}
