//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMMS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class PerformanceList
    {
        public int PerformanceListID { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Please provide a time.")]
        [Display(Name = "Time")]
        public System.TimeSpan PerformanceTime { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Please provide a music sheet.")]
        [Display(Name = "Music Sheet")]
        public int MusicSheetID { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Please provide a performance.")]
        [Display(Name = "Performance")]
        public int PerformanceID { get; set; }
    
        public virtual MusicSheet MusicSheet { get; set; }
        public virtual Performance Performance { get; set; }
    }
}
