//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMMS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IN705_201802_arulr1Entities1 : DbContext
    {
        public IN705_201802_arulr1Entities1()
            : base("name=IN705_201802_arulr1Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Ensemble> Ensembles { get; set; }
        public virtual DbSet<EnsembleGroup> EnsembleGroups { get; set; }
        public virtual DbSet<FeeStructire> FeeStructires { get; set; }
        public virtual DbSet<Instrument> Instruments { get; set; }
        public virtual DbSet<InstrumentAssert> InstrumentAsserts { get; set; }
        public virtual DbSet<InstrumentCondition> InstrumentConditions { get; set; }
        public virtual DbSet<Music> Musics { get; set; }
        public virtual DbSet<PaymentStatu> PaymentStatus { get; set; }
        public virtual DbSet<Performance> Performances { get; set; }
        public virtual DbSet<Student> Students { get; set; }
        public virtual DbSet<Technician> Technicians { get; set; }
        public virtual DbSet<Tutor> Tutors { get; set; }
        public virtual DbSet<TutorLevel> TutorLevels { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserRole> UserRoles { get; set; }
        public virtual DbSet<CourseLevel> CourseLevels { get; set; }
        public virtual DbSet<Enrolment> Enrolments { get; set; }
        public virtual DbSet<InstrumentHire> InstrumentHires { get; set; }
        public virtual DbSet<InstumentService> InstumentServices { get; set; }
        public virtual DbSet<Lesson> Lessons { get; set; }
        public virtual DbSet<Lessonbatch> Lessonbatches { get; set; }
        public virtual DbSet<LessonType> LessonTypes { get; set; }
        public virtual DbSet<MusicSheet> MusicSheets { get; set; }
        public virtual DbSet<Payment> Payments { get; set; }
        public virtual DbSet<PerformanceList> PerformanceLists { get; set; }
    }
}
